//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rehber.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAyarlar
    {
        public int ID { get; set; }
        public string Anahtar { get; set; }
        public string Deger { get; set; }
    }
}
